### PR TITLE
Added option to create column with some types of actions buttons independently 

### PR DESCRIPTION
**Pull request by eronalves**
I implemented based on PR # 467 the option to include action buttons regardless of the purpose of the action (without the need to be an edit or delete action).

You can choose between three button layouts: SIMPLE, GROUP, and DROPDOWN.

For this, I add an object in the config to share callbacks called 'api'.

`
public config:any = {
    paging: true,
    sorting: {columns: this.columns},
    filtering: {filterString: ''},
    className: ['table-striped', 'table-bordered'],
    api: {
        onEdit: this.onEdit.bind(this),
        onDelete: this.onDelete.bind(this)
      }
  };
`

And in actions declaration:

` 
 {
      title: 'Simple',
      name: 'actionSimple',
      actions: {
        type: 'simple',
        buttons: [
          {
            name: 'edit',
            title: 'Edit',
            styleClass: 'btn btn-primary',
            styleIcon: 'fa fa-pencil',
            action: 'onEdit'
          }
        ]
      }
    },
`

I hope a discuss about this implementation and a possible merge.

Thanks!

### CODE REVIEW

**Comment by mtpultz** [comment]
@eronalves will this allow for rendering components?  Like adding a angular material button with menu like the example for menu https://material.angular.io/components/component/menu?

**Comment by eronalves** [comment]
@mtpultz yep, I'm using the dropdown from @valorkin 's project https://github.com/valor-software/ngx-bootstrap, but my PR must be updated with the last version.

The idea is configure columns action in any position (first column, last column, etc;) and choose between three types of buttons (Single, Group or dropdown) and callbacks. 

I tried to use my PR in production but is impossible to load angular2 packages directly from github with npm (maybe in the future), anyway, I implemented a datatable with this idea and others options but I need to publish on npm.

**Comment by raviada** [comment]
@eronalves, I really liked the simplicity of this grid. With your addition, it really makes it more useful. Did you get a chance to publish your changes to npm or even created your own repo? I would like to get the code with your changes merged to it. Please let me know if you are planning to do this, I am in need of an urgent implementation.

Thanks in advance.

**Comment by eronalves** [comment]
Hi @raviada,

I need more time to adjust simple issues before publish on npm.
My plan is publish at the end of this month.

Thanks for your interesting.

**Review by bhazied — APPROVED** [review]

**Comment by eronalves** [comment]
@raviada @mtpultz 

I created this [repo](https://github.com/magic-software-lab/ngx-magic-table) to share my own datatable.
It's simple by now, but I will create a roadmap to list features than I need in my personal projects.

If you want, we can discuss new possibilities and fix issues.

I don't know the focus of Valor Software, but seems this project is secondary at moment.

[ngx-magic-table](https://github.com/magic-software-lab/ngx-magic-table)
[npm](https://www.npmjs.com/package/@magic-software/ngx-magic-table)

**Comment by valorkin** [comment]
I can give all required access, qa help, and help to publish new versions, if you would love to maintain this library

**Comment by themese** [comment]
Any updates on this PR? I think it's very interesting and could be very useful for all of us

**Review by dimjava — COMMENTED** [review]
Did you check dropdown type ?
When I click the main button nothing happens.

UPD. Everything is ok, my bad.

**Comment by stephenad** [comment]
HI @eronalves,

I have been trying your magic table demo as I need buttons on my table but am having issues, I have used the basic ng2-table from [Valor web site ](http://valor-software.com/ng2-table/) as my starting point and apart from buttons and check box columns my table is almost as I want it.

First question can your  simple buttons demo [https://magic-software-lab.github.io/ngx-magic-table/demos] work on Angular 2 as I have inherited a system a client was changes on by it is on angular 2 and upgrading it to 4 at the moment is not an option.

The two issues I am having may relate to the fact I am not on the newer angular but for the columns I am getting the error message:
`EXCEPTION: item[column.name] is undefined`
 My columns are in a separate file (below) and this is call from the main file.
`
export const UserTableColumns:Array<any> = 
[
    {title: 'ID', name: 'id'},
    {title: 'Full Name', name: 'full_name'},
    {title: 'User Name', name: 'username'},
    {title: 'Email', name: 'email'},
        {
        title: 'Edit',
        actions: {
          type: 'simple',
          buttons: [
            {
              title: 'Edit',
              styleClass: 'btn btn-primary',
              styleIcon: 'fa fa-pencil',
              action: 'edit'
            }
          ]
        }
      },
      {
        title: 'Delete',
        actions: {
          type: 'simple',
          buttons: [
            {
              title: 'Delete',
              styleClass: 'btn btn-danger',
              styleIcon: 'fa fa-times',
              action: 'delete'
            }
          ]
        }
      }
    // {title: '', name: 'id', component: UserTableButtons, init: this._func, sort: false, filter: false }
];`

Secondly when I put the  table options code in the html file and i get the following message in the console:

`Can't bind to 'tableOptions' since it isn't a known property of 'ng-table'.`

`<ng-table id="UserList" [config]="config.sorting"
           (tableChanged)="onChangeTable(config)"
           [rows]="rows" [columns]="columns"
           [tableOptions]="tableOptions">
</ng-table>`

Below is my table.ts file:

`
import { Component, OnInit, OnDestroy, EventEmitter } from '@angular/core';
import { Router } from '@angular/router';
import { UserTableColumns } from '../userarea/user-tablecolumns.component';

@Component({
	selector: 'app-userstable',
	templateUrl: '../ts_html/user-table.component.html',
})

export class UserTableComponent implements OnInit, OnDestroy {

	userlist: UserDetailInfo[];
	currentuser: UserDetailInfo;
	isloading: boolean;
	onUserSelected: EventEmitter<UserDetailInfo>;

	rows: Array<any> = [];
	columns = UserTableColumns;  //this is now pointing to my 'tablecoumns component'
	
	public page: number = 1;
	public itemsPerPage: number = 10;
	public maxSize: number = 5;
	public numPages: number = 1;
	public length: number = 0;

	public config: any = {
		paging: true,
		sorting: { columns: this.columns },
		filtering: { filterString: '' },
		className: ['table-striped', 'table-bordered', 'width: 100% !important']
	};

	// private data:Array<any> = TableData;
	private data: Array<any>;
	private initialConfiguration: boolean;

  public tableOptions: any = {
      api: {
        edit: this.onEdit,
        delete: this.onDelete
      }
  };

	constructor
		(
		private router: Router,		
		) {
		this.onUserSelected = new EventEmitter<UserDetailInfo>();
		this.initialConfiguration = false; // setting initialConfiguration initial state
		
	}

	public ngOnInit(): void {
		console.log('TableDemoComponent.ngOnInit()');
		this.getUserList();
	}

	getUserList() {
		this.isloading = true;
		this.userAuthService.getUserList()
			.subscribe(mydata => {
				//Changed this.userlist to be this.data as it is declared above
				this.data = mydata;
				//added if statement to check if we have data assigned to this.data before calling any other functions
				if (!this.initialConfiguration) {
					this.length = this.data.length;
					this.onChangeTable(this.config);
					this.initialConfiguration = true;
				}
			}, //Bind to view
			error => {
				// Log errors if any
				this.aMS.messageLog("Errors", "Error", "Error - retrieving users", "Error loading user list.");
				this.isloading = false;
				console.log(error);
			},
			() => {
				this.isloading = false;
			});
	}

	public changePage(page: any, data: Array<any> = this.data): Array<any> {
		let start = (page.page - 1) * page.itemsPerPage;
		let end = page.itemsPerPage > -1 ? (start + page.itemsPerPage) : data.length;
		return data.slice(start, end);
	}

	public changeSort(data: any, config: any): any {
		if (!config.sorting) {
			return data;
		}

		let columns = this.config.sorting.columns || [];
		let columnName: string = void 0;
		let sort: string = void 0;

		for (let i = 0; i < columns.length; i++) {
			if (columns[i].sort !== '' && columns[i].sort !== false) {
				columnName = columns[i].name;
				sort = columns[i].sort;
			}
		}

		if (!columnName) {
			return data;
		}

		// simple sorting
		return data.sort((previous: any, current: any) => {
			if (previous[columnName] > current[columnName]) {
				return sort === 'desc' ? -1 : 1;
			} else if (previous[columnName] < current[columnName]) {
				return sort === 'asc' ? -1 : 1;
			}
			return 0;
		});
	}

	public changeFilter(data: any, config: any): any {
		let filteredData: Array<any> = data;
		this.columns.forEach((column: any) => {
			if (column.filtering) {
				filteredData = filteredData.filter((item: any) => {
					return item[column.name].tostring().toLowerCase().slice(18).match(column.filtering.filterString.toString.toLowerCase());
				});
			}
		});

		if (!config.filtering) {
			return filteredData;
		}

		if (config.filtering.columnName) {
			return filteredData.filter((item: any) =>
				item[config.filtering.columnName].tostring().toLowerCase().match(this.config.filtering.filterString.toLowerCase()));
		}

		let tempArray: Array<any> = [];
		filteredData.forEach((item: any) => {
			let flag = false;
			this.columns.forEach((column: any) => {	
					if (item[column.name].toString().toLowerCase().match(this.config.filtering.filterString.toLowerCase())) {
						flag = true;					
				}
			});
			if (flag) {
				tempArray.push(item);
			}
		});
		filteredData = tempArray;

		return filteredData;
	}

**_//code from your project_**

    private onEdit(data: any) {
    alert('Editing ' + data.description);
  }
 
  private onDelete(data: any) {
    alert('Deleting ' + data.description);
  }

public onChangeTable(config: any, page: any = { page: this.page, itemsPerPage: this.itemsPerPage }): any {
		if (config.filtering) {
			Object.assign(this.config.filtering, config.filtering);
		}

		if (config.sorting) {
			Object.assign(this.config.sorting, config.sorting);
		}

		let filteredData = this.changeFilter(this.data, this.config);
		let sortedData = this.changeSort(filteredData, this.config);
		this.rows = page && config.paging ? this.changePage(page, sortedData) : sortedData;
		this.length = sortedData.length;
	}
}
`

Thanks in advance
Andy

**Review by templarfelix — APPROVED** [review]

**Pull request closed without merging**
