### PR TITLE
Added click on a row event

### PR DESCRIPTION
**Pull request by Pokom**
I'm using this in a project and one of the things I need to do is filter down on tables. So if I click on a row, it'll emit an event back to the component that created the table saying what row was clicked. I can use this information to pull up the relevant account information. 

I'm not sure how this fits into the grand scheme of things for the project, but there's numerous other areas that I'm willing to build out that fit particularly well into how I intend on using the product. Let me know what i can do to better fit into the project!

### CODE REVIEW

**Comment by wangfenjin** [comment]
Hi team, could you please take a look on this MR?

I'd like to use this feature...

**Comment by paolomaffei** [comment]
+1

**Comment by paolomaffei** [comment]
in the meanwhile, could someone explain step-by-step how I can use this version? pulling directly from github doesn't seem to work because the package doesn't get built (ts files are there, but not the "bundles" that you get from the npm package).
I even tried creating another npm package, but:
1) if it's not called "ng2-table" it will error when compiling the bundles
2) if it's called "ng2-table" I can't publish it (obviously)
so how do I import it into an angular-cli (broccoli, not webpack) project?

**Comment by otelnov** [comment]
https://github.com/valor-software/ng2-table/pull/303

**Pull request closed without merging**
