### PR TITLE
Modified code so that table works with angular 2 rc1

### PR DESCRIPTION
**Pull request by shahmirn**
Fixes issue #135

### CODE REVIEW

**Comment by valorkin** [comment]
Looks good! Thanks for your help!

**Comment by vladjerca** [comment]
@shahmirn 
The branch works, although you did not update the HTML template loops to use 'let'.

'ng-table.component.ts'
```html
<tr *ngFor="#row of rows">
        <td *ngFor="#column of columns">{{getData(row, column.name)}}</td>
</tr>
```

Should be:

```html
<tr *ngFor="let row of rows">
        <td *ngFor="let column of columns">{{getData(row, column.name)}}</td>
</tr>
```

 I think must be done before this gets merged, these have been marked as deprecated since beta15 if I'm not mistaken.

And thanks for taking the time to make the changes!

**Comment by valorkin** [comment]
Will be updated today, latest tomorrow

**Comment by valorkin** [comment]
Merged, updating to release flow of other ng2 modules

**Comment by valorkin** [comment]
Thanks for your help!

**Comment by valorkin** [comment]
@shahmirn if you want to develop this module further I can give you write access
just drop me a note :)

**Comment by shahmirn** [comment]
@valorkin Write access would be great. There's a few more features that I need for my use-case that I'll need to add, one of them being the ability to support mark-up in the columns.

**Comment by valorkin** [comment]
Here we go :)
Welcome to ng2-team :)

**Pull request merged**
